// <auto-generated />
namespace DrinkIt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddBeverageImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBeverageImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202104111818043_AddBeverageImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
